### ISSUE TITLE
windows sees Rhino as a trojan

### ISSUE THREAD

**Issue by chopspry** [KubeJS-Mods/Rhino#6]
![image](https://user-images.githubusercontent.com/69838357/129978664-a3167ea6-ce01-4a35-bfe7-926978e80bdc.png)
yeah uh my windows is giving me popups about how Rhino is a trojan script.

**Comment by MaxNeedsSnacks** [comment]
Yeah, this is a known false-positive issue unfortunately, and it seems to be happening to quite a few mods now (so much so that CurseForge mentioned it in their Discord announcements / app changelog)

Until this is fixed, I recommend you either stay on the old version or just manually trust the new one
